"""Stack-specific monitoring facade.

This module provides :class:`StackMonitor`, the high-level API used by the
original Epilogue stack tracing example.  It is independent from the generic
batch persistence API in :mod:`epilogue.batch`; both APIs remain Python-only.
"""

from __future__ import annotations

from typing import Generic, TypeVar

from .snapshot import StackSnapshot
from .trace    import StackTrace

T = TypeVar('T')


class StackMonitor(Generic[T]):
    """Record a typed history of stack operations.

    ``StackMonitor`` owns an in-memory :class:`~epilogue.trace.StackTrace` and
    provides the small facade used by callers that want to associate an
    operation and optional argument with a stack snapshot.

    The type parameter ``T`` is the element/argument type being traced.

    Notes:
        This monitor is an in-memory diagnostic trace.  For generic append-only
        batch persistence use :class:`epilogue.BatchMonitor`.
    """

    def __init__(self) -> None:
        """Initialize an empty stack trace."""
        self.__trace: StackTrace[T] = StackTrace[T]()

    def log(
        self,
        operation: str,
        argument: T | None,
        snapshot: StackSnapshot[T | None],
    ) -> None:
        """Append one stack operation to the trace.

        Args:
            operation: Human-readable operation name such as ``"PUSH"`` or
                ``"RESTORE"``.
            argument: Optional value associated with the operation.
            snapshot: Immutable stack state captured after or around the
                operation being recorded.

        Returns:
            None.
        """
        self.__trace.log(
            operation,
            argument,
            snapshot,
        )

    def dump(self) -> str:
        """Render the complete stack trace as human-readable text.

        Returns:
            Multi-line textual ledger generated by
            :meth:`epilogue.trace.StackTrace.dump`.
        """
        return self.__trace.dump()
